/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dragonboard.swig;

public class gpio_list {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected gpio_list(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(gpio_list obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                gpioJNI.delete_gpio_list(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void setG(SWIGTYPE_p_gpio value) {
        gpioJNI.gpio_list_g_set(swigCPtr, this, SWIGTYPE_p_gpio.getCPtr(value));
    }

    public SWIGTYPE_p_gpio getG() {
        long cPtr = gpioJNI.gpio_list_g_get(swigCPtr, this);
        return (cPtr == 0) ? null : new SWIGTYPE_p_gpio(cPtr, false);
    }

    public void setNext(gpio_list value) {
        gpioJNI.gpio_list_next_set(swigCPtr, this, gpio_list.getCPtr(value), value);
    }

    public gpio_list getNext() {
        long cPtr = gpioJNI.gpio_list_next_get(swigCPtr, this);
        return (cPtr == 0) ? null : new gpio_list(cPtr, false);
    }

    public gpio_list() {
        this(gpioJNI.new_gpio_list(), true);
    }
    
}
