/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dragonboard.swig;

public class gpioJNI {
    static {
        System.loadLibrary("gpio");
    }

    public final static native void gpio_list_g_set(long jarg1, gpio_list jarg1_, long jarg2);

    public final static native long gpio_list_g_get(long jarg1, gpio_list jarg1_);

    public final static native void gpio_list_next_set(long jarg1, gpio_list jarg1_, long jarg2, gpio_list jarg2_);

    public final static native long gpio_list_next_get(long jarg1, gpio_list jarg1_);

    public final static native long new_gpio_list();

    public final static native void delete_gpio_list(long jarg1);

    public final static native void gpios_set(long jarg1, gpio_list jarg1_);

    public final static native long gpios_get();

    public final static native void config_set(long jarg1);

    public final static native long config_get();

    public final static native long gpio_id(String jarg1);

    public final static native long gpio_by_letter(char jarg1);

    public final static native long gpio_by_pin(char jarg1);

    public final static native int gpio_open(long jarg1, String jarg2);

    public final static native int digitalRead(long jarg1);

    public final static native int digitalWrite(long jarg1, long jarg2);
}
