/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dragonboard.swig;

public class gpio {
    public static void setGpios(gpio_list value) {
        gpioJNI.gpios_set(gpio_list.getCPtr(value), value);
    }

    public static gpio_list getGpios() {
        long cPtr = gpioJNI.gpios_get();
        return (cPtr == 0) ? null : new gpio_list(cPtr, false);
    }

    public static void setConfig(SWIGTYPE_p_board_config value) {
        gpioJNI.config_set(SWIGTYPE_p_board_config.getCPtr(value));
    }

    public static SWIGTYPE_p_board_config getConfig() {
        long cPtr = gpioJNI.config_get();
        return (cPtr == 0) ? null : new SWIGTYPE_p_board_config(cPtr, false);
    }

    public static long gpio_id(String pin_name) {
        return gpioJNI.gpio_id(pin_name);
    }

    public static long gpio_by_letter(char alpha) {
        return gpioJNI.gpio_by_letter(alpha);
    }

    public static long gpio_by_pin(char pin_number) {
        return gpioJNI.gpio_by_pin(pin_number);
    }

    public static int gpio_open(long gpio_id, String direction) {
        return gpioJNI.gpio_open(gpio_id, direction);
    }

    public static int digitalRead(long gpio_id) {
        return gpioJNI.digitalRead(gpio_id);
    }

    public static int digitalWrite(long gpio_id, long value) {
        return gpioJNI.digitalWrite(gpio_id, value);
    }

}
